### ISSUE TITLE
Move clarity contracts to own folder

### ISSUE THREAD

**Issue by friedger** [bitcoin-nfts/bitcoin-colors#39] opened 2022-12-31 11:10 UTC
Currently, clarinet config is a top level file. All clarity files should be located in a folder like `backend-public`

**Comment by whoabuddy** [comment] 2023-01-02 16:38
This repo was intended for the backend code - a separate repo will be created for the frontend per #28, and a separate repo exists for the conversion tool so it can be published as a separate package: [bitcoin-colors-generator](https://github.com/bitcoin-nfts/bitcoin-colors-generator).

With that in mind would you still move all the Clarity files / clarinet config?

**Comment by whoabuddy** [comment] 2023-01-19 15:39
Closing this out but feel free to re-open if anyone thinks this should still be reorganized.

**Closed by whoabuddy** 2023-01-19 15:39 UTC
Labels: contract
